secrets:
  # name of secret to fetch from secret store
  #- secret: SECRET_EXAMPLE
  # name of env variable to set in target env with the fetched secret value
  #  env_var: ENV_SECRET_EXAMPLE
  - secret: SECRET_SCHEDULER_APP_PRIVATE_KEY
    env_var: SCHEDULER_APP_PRIVATE_KEY_ENV