// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.2
// source: app_auth.proto

package dstsprotos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppAuthenticationChallengeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Common request header including protocol version & request identifier.
	Header *DstsRequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Version of the AppAuthenticationChallengeRequest message.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Unique identifier of the registered app requesting authentication.
	AppId string `protobuf:"bytes,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
}

func (x *AppAuthenticationChallengeRequest) Reset() {
	*x = AppAuthenticationChallengeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_auth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppAuthenticationChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppAuthenticationChallengeRequest) ProtoMessage() {}

func (x *AppAuthenticationChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_auth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppAuthenticationChallengeRequest.ProtoReflect.Descriptor instead.
func (*AppAuthenticationChallengeRequest) Descriptor() ([]byte, []int) {
	return file_app_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AppAuthenticationChallengeRequest) GetHeader() *DstsRequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *AppAuthenticationChallengeRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AppAuthenticationChallengeRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type AppAuthenticationChallengeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Common response header including protocol version & request identifier.
	Header *DstsResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// The challenge string generated by DSTS for this AppAuthentication request.
	Challenge string `protobuf:"bytes,2,opt,name=challenge,proto3" json:"challenge,omitempty"`
	// Expiry timestamp.
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
}

func (x *AppAuthenticationChallengeResponse) Reset() {
	*x = AppAuthenticationChallengeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_auth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppAuthenticationChallengeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppAuthenticationChallengeResponse) ProtoMessage() {}

func (x *AppAuthenticationChallengeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_auth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppAuthenticationChallengeResponse.ProtoReflect.Descriptor instead.
func (*AppAuthenticationChallengeResponse) Descriptor() ([]byte, []int) {
	return file_app_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AppAuthenticationChallengeResponse) GetHeader() *DstsResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *AppAuthenticationChallengeResponse) GetChallenge() string {
	if x != nil {
		return x.Challenge
	}
	return ""
}

func (x *AppAuthenticationChallengeResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type AppAuthenticationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Common request header including protocol version & request identifier.
	Header *DstsRequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Version of the AppAuthenticationChallengeRequest message.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Unique identifier of the registered app requesting authentication.
	AppId string `protobuf:"bytes,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	// The type of assertion submitted by the caller in the assertion field, to
	// authenticate itself.
	AssertionType string `protobuf:"bytes,4,opt,name=assertion_type,json=assertionType,proto3" json:"assertion_type,omitempty"`
	// The signed assertion submitted by the caller to authenticate itself.
	Assertion string `protobuf:"bytes,5,opt,name=assertion,proto3" json:"assertion,omitempty"`
}

func (x *AppAuthenticationRequest) Reset() {
	*x = AppAuthenticationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_auth_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppAuthenticationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppAuthenticationRequest) ProtoMessage() {}

func (x *AppAuthenticationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_auth_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppAuthenticationRequest.ProtoReflect.Descriptor instead.
func (*AppAuthenticationRequest) Descriptor() ([]byte, []int) {
	return file_app_auth_proto_rawDescGZIP(), []int{2}
}

func (x *AppAuthenticationRequest) GetHeader() *DstsRequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *AppAuthenticationRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AppAuthenticationRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *AppAuthenticationRequest) GetAssertionType() string {
	if x != nil {
		return x.AssertionType
	}
	return ""
}

func (x *AppAuthenticationRequest) GetAssertion() string {
	if x != nil {
		return x.Assertion
	}
	return ""
}

type AppAuthenticationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Common response header including protocol version & request identifier.
	Header *DstsResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// The access token generated by DSTS for this AppAuthentication request.
	AccessToken string `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// Expiry timestamp.
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
}

func (x *AppAuthenticationResponse) Reset() {
	*x = AppAuthenticationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_auth_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppAuthenticationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppAuthenticationResponse) ProtoMessage() {}

func (x *AppAuthenticationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_auth_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppAuthenticationResponse.ProtoReflect.Descriptor instead.
func (*AppAuthenticationResponse) Descriptor() ([]byte, []int) {
	return file_app_auth_proto_rawDescGZIP(), []int{3}
}

func (x *AppAuthenticationResponse) GetHeader() *DstsResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *AppAuthenticationResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *AppAuthenticationResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

var File_app_auth_proto protoreflect.FileDescriptor

var file_app_auth_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x61, 0x70, 0x70, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0c, 0x6b, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x6e, 0x2e, 0x64, 0x73, 0x74, 0x73, 0x1a, 0x0c,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8d, 0x01,
	0x0a, 0x21, 0x41, 0x70, 0x70, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x37, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6b, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x6e, 0x2e, 0x64, 0x73,
	0x74, 0x73, 0x2e, 0x44, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x22, 0xb7, 0x01,
	0x0a, 0x22, 0x41, 0x70, 0x70, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6b, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x6e, 0x2e, 0x64,
	0x73, 0x74, 0x73, 0x2e, 0x44, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x1c,
	0x0a, 0x09, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x12, 0x39, 0x0a, 0x0a,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x65, 0x78,
	0x70, 0x69, 0x72, 0x65, 0x73, 0x41, 0x74, 0x22, 0xc9, 0x01, 0x0a, 0x18, 0x41, 0x70, 0x70, 0x41,
	0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x37, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6b, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x6e, 0x2e, 0x64,
	0x73, 0x74, 0x73, 0x2e, 0x44, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x18, 0x0a,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x25,
	0x0a, 0x0e, 0x61, 0x73, 0x73, 0x65, 0x72, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x73, 0x73, 0x65, 0x72, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x73, 0x73, 0x65, 0x72, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x73, 0x73, 0x65, 0x72, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0xb3, 0x01, 0x0a, 0x19, 0x41, 0x70, 0x70, 0x41, 0x75, 0x74, 0x68, 0x65,
	0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x38, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x20, 0x2e, 0x6b, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x6e, 0x2e, 0x64, 0x73, 0x74, 0x73,
	0x2e, 0x44, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x61,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x39,
	0x0a, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x41, 0x74, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x61, 0x7a, 0x63, 0x2e, 0x65, 0x78, 0x74, 0x2e, 0x68, 0x70, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x4b, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x6e, 0x2f, 0x64, 0x73, 0x74, 0x73, 0x2f,
	0x64, 0x73, 0x74, 0x73, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_app_auth_proto_rawDescOnce sync.Once
	file_app_auth_proto_rawDescData = file_app_auth_proto_rawDesc
)

func file_app_auth_proto_rawDescGZIP() []byte {
	file_app_auth_proto_rawDescOnce.Do(func() {
		file_app_auth_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_auth_proto_rawDescData)
	})
	return file_app_auth_proto_rawDescData
}

var file_app_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_app_auth_proto_goTypes = []interface{}{
	(*AppAuthenticationChallengeRequest)(nil),  // 0: krypton.dsts.AppAuthenticationChallengeRequest
	(*AppAuthenticationChallengeResponse)(nil), // 1: krypton.dsts.AppAuthenticationChallengeResponse
	(*AppAuthenticationRequest)(nil),           // 2: krypton.dsts.AppAuthenticationRequest
	(*AppAuthenticationResponse)(nil),          // 3: krypton.dsts.AppAuthenticationResponse
	(*DstsRequestHeader)(nil),                  // 4: krypton.dsts.DstsRequestHeader
	(*DstsResponseHeader)(nil),                 // 5: krypton.dsts.DstsResponseHeader
	(*timestamppb.Timestamp)(nil),              // 6: google.protobuf.Timestamp
}
var file_app_auth_proto_depIdxs = []int32{
	4, // 0: krypton.dsts.AppAuthenticationChallengeRequest.header:type_name -> krypton.dsts.DstsRequestHeader
	5, // 1: krypton.dsts.AppAuthenticationChallengeResponse.header:type_name -> krypton.dsts.DstsResponseHeader
	6, // 2: krypton.dsts.AppAuthenticationChallengeResponse.expires_at:type_name -> google.protobuf.Timestamp
	4, // 3: krypton.dsts.AppAuthenticationRequest.header:type_name -> krypton.dsts.DstsRequestHeader
	5, // 4: krypton.dsts.AppAuthenticationResponse.header:type_name -> krypton.dsts.DstsResponseHeader
	6, // 5: krypton.dsts.AppAuthenticationResponse.expires_at:type_name -> google.protobuf.Timestamp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_app_auth_proto_init() }
func file_app_auth_proto_init() {
	if File_app_auth_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_app_auth_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppAuthenticationChallengeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_auth_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppAuthenticationChallengeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_auth_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppAuthenticationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_auth_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppAuthenticationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_auth_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_auth_proto_goTypes,
		DependencyIndexes: file_app_auth_proto_depIdxs,
		MessageInfos:      file_app_auth_proto_msgTypes,
	}.Build()
	File_app_auth_proto = out.File
	file_app_auth_proto_rawDesc = nil
	file_app_auth_proto_goTypes = nil
	file_app_auth_proto_depIdxs = nil
}
