// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.2
// source: enrollment_token.proto

package dstsprotos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnrollmentToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Enrollment token
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// Enrollment token issued timestamp.
	IssuedTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=issued_time,json=issuedTime,proto3" json:"issued_time,omitempty"`
	// Enrollment token expiry timestamp.
	ExpiryTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expiry_time,json=expiryTime,proto3" json:"expiry_time,omitempty"`
}

func (x *EnrollmentToken) Reset() {
	*x = EnrollmentToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_enrollment_token_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnrollmentToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollmentToken) ProtoMessage() {}

func (x *EnrollmentToken) ProtoReflect() protoreflect.Message {
	mi := &file_enrollment_token_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollmentToken.ProtoReflect.Descriptor instead.
func (*EnrollmentToken) Descriptor() ([]byte, []int) {
	return file_enrollment_token_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollmentToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *EnrollmentToken) GetIssuedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedTime
	}
	return nil
}

func (x *EnrollmentToken) GetExpiryTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiryTime
	}
	return nil
}

type CreateEnrollmentTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Common request header including protocol version & request identifier.
	Header *DstsRequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Version of the CreateEnrollmentTokenRequest message.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Unique identifier for the tenant (Tenant ID).
	Tid string `protobuf:"bytes,3,opt,name=tid,proto3" json:"tid,omitempty"`
	// Enrollment token lifetime configured for the tenant at the ES.
	// 0 or not specified -> 30 days
	// -1 -> 5 years (max)
	// other values (1 - 5 years) -> specified value
	TokenLifetimeDays int32 `protobuf:"varint,4,opt,name=token_lifetime_days,json=tokenLifetimeDays,proto3" json:"token_lifetime_days,omitempty"`
}

func (x *CreateEnrollmentTokenRequest) Reset() {
	*x = CreateEnrollmentTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_enrollment_token_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateEnrollmentTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEnrollmentTokenRequest) ProtoMessage() {}

func (x *CreateEnrollmentTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_enrollment_token_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEnrollmentTokenRequest.ProtoReflect.Descriptor instead.
func (*CreateEnrollmentTokenRequest) Descriptor() ([]byte, []int) {
	return file_enrollment_token_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEnrollmentTokenRequest) GetHeader() *DstsRequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *CreateEnrollmentTokenRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CreateEnrollmentTokenRequest) GetTid() string {
	if x != nil {
		return x.Tid
	}
	return ""
}

func (x *CreateEnrollmentTokenRequest) GetTokenLifetimeDays() int32 {
	if x != nil {
		return x.TokenLifetimeDays
	}
	return 0
}

type CreateEnrollmentTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Common response header including protocol version & request identifier.
	Header *DstsResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Enrollment token.
	Token *EnrollmentToken `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *CreateEnrollmentTokenResponse) Reset() {
	*x = CreateEnrollmentTokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_enrollment_token_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateEnrollmentTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEnrollmentTokenResponse) ProtoMessage() {}

func (x *CreateEnrollmentTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_enrollment_token_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEnrollmentTokenResponse.ProtoReflect.Descriptor instead.
func (*CreateEnrollmentTokenResponse) Descriptor() ([]byte, []int) {
	return file_enrollment_token_proto_rawDescGZIP(), []int{2}
}

func (x *CreateEnrollmentTokenResponse) GetHeader() *DstsResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *CreateEnrollmentTokenResponse) GetToken() *EnrollmentToken {
	if x != nil {
		return x.Token
	}
	return nil
}

type GetEnrollmentTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Common request header including protocol version & request identifier.
	Header *DstsRequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Version of the GetEnrollmentTokenRequest message.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Unique identifier for the tenant (Tenant ID).
	Tid string `protobuf:"bytes,3,opt,name=tid,proto3" json:"tid,omitempty"`
}

func (x *GetEnrollmentTokenRequest) Reset() {
	*x = GetEnrollmentTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_enrollment_token_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEnrollmentTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnrollmentTokenRequest) ProtoMessage() {}

func (x *GetEnrollmentTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_enrollment_token_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnrollmentTokenRequest.ProtoReflect.Descriptor instead.
func (*GetEnrollmentTokenRequest) Descriptor() ([]byte, []int) {
	return file_enrollment_token_proto_rawDescGZIP(), []int{3}
}

func (x *GetEnrollmentTokenRequest) GetHeader() *DstsRequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetEnrollmentTokenRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetEnrollmentTokenRequest) GetTid() string {
	if x != nil {
		return x.Tid
	}
	return ""
}

type GetEnrollmentTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Common response header including protocol version & request identifier.
	Header *DstsResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Enrollment token.
	Token *EnrollmentToken `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *GetEnrollmentTokenResponse) Reset() {
	*x = GetEnrollmentTokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_enrollment_token_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEnrollmentTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnrollmentTokenResponse) ProtoMessage() {}

func (x *GetEnrollmentTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_enrollment_token_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnrollmentTokenResponse.ProtoReflect.Descriptor instead.
func (*GetEnrollmentTokenResponse) Descriptor() ([]byte, []int) {
	return file_enrollment_token_proto_rawDescGZIP(), []int{4}
}

func (x *GetEnrollmentTokenResponse) GetHeader() *DstsResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetEnrollmentTokenResponse) GetToken() *EnrollmentToken {
	if x != nil {
		return x.Token
	}
	return nil
}

type DeleteEnrollmentTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Common request header including protocol version & request identifier.
	Header *DstsRequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Version of the DeleteEnrollmentTokenRequest message.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Unique identifier for the tenant (Tenant ID).
	Tid string `protobuf:"bytes,3,opt,name=tid,proto3" json:"tid,omitempty"`
}

func (x *DeleteEnrollmentTokenRequest) Reset() {
	*x = DeleteEnrollmentTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_enrollment_token_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteEnrollmentTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEnrollmentTokenRequest) ProtoMessage() {}

func (x *DeleteEnrollmentTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_enrollment_token_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEnrollmentTokenRequest.ProtoReflect.Descriptor instead.
func (*DeleteEnrollmentTokenRequest) Descriptor() ([]byte, []int) {
	return file_enrollment_token_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteEnrollmentTokenRequest) GetHeader() *DstsRequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *DeleteEnrollmentTokenRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DeleteEnrollmentTokenRequest) GetTid() string {
	if x != nil {
		return x.Tid
	}
	return ""
}

type DeleteEnrollmentTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Common response header including protocol version & request identifier.
	Header *DstsResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Deletion timestamp.
	DeleteTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=delete_time,json=deleteTime,proto3" json:"delete_time,omitempty"`
}

func (x *DeleteEnrollmentTokenResponse) Reset() {
	*x = DeleteEnrollmentTokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_enrollment_token_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteEnrollmentTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEnrollmentTokenResponse) ProtoMessage() {}

func (x *DeleteEnrollmentTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_enrollment_token_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEnrollmentTokenResponse.ProtoReflect.Descriptor instead.
func (*DeleteEnrollmentTokenResponse) Descriptor() ([]byte, []int) {
	return file_enrollment_token_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteEnrollmentTokenResponse) GetHeader() *DstsResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *DeleteEnrollmentTokenResponse) GetDeleteTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DeleteTime
	}
	return nil
}

type ValidateEnrollmentTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Common request header including protocol version & request identifier.
	Header *DstsRequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Version of the DeleteEnrollmentTokenRequest message.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Enrollment token.
	Token string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *ValidateEnrollmentTokenRequest) Reset() {
	*x = ValidateEnrollmentTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_enrollment_token_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateEnrollmentTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateEnrollmentTokenRequest) ProtoMessage() {}

func (x *ValidateEnrollmentTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_enrollment_token_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateEnrollmentTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateEnrollmentTokenRequest) Descriptor() ([]byte, []int) {
	return file_enrollment_token_proto_rawDescGZIP(), []int{7}
}

func (x *ValidateEnrollmentTokenRequest) GetHeader() *DstsRequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ValidateEnrollmentTokenRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ValidateEnrollmentTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ValidateEnrollmentTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Common response header including protocol version & request identifier.
	Header *DstsResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Unique identifier for the tenant (Tenant ID) to which the enrollment
	// token belongs.
	Tid string `protobuf:"bytes,2,opt,name=tid,proto3" json:"tid,omitempty"`
	// Specifies whether the presented enrollment token is valid.
	IsValid bool `protobuf:"varint,3,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
}

func (x *ValidateEnrollmentTokenResponse) Reset() {
	*x = ValidateEnrollmentTokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_enrollment_token_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateEnrollmentTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateEnrollmentTokenResponse) ProtoMessage() {}

func (x *ValidateEnrollmentTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_enrollment_token_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateEnrollmentTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateEnrollmentTokenResponse) Descriptor() ([]byte, []int) {
	return file_enrollment_token_proto_rawDescGZIP(), []int{8}
}

func (x *ValidateEnrollmentTokenResponse) GetHeader() *DstsResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ValidateEnrollmentTokenResponse) GetTid() string {
	if x != nil {
		return x.Tid
	}
	return ""
}

func (x *ValidateEnrollmentTokenResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

var File_enrollment_token_proto protoreflect.FileDescriptor

var file_enrollment_token_proto_rawDesc = []byte{
	0x0a, 0x16, 0x65, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6b, 0x72, 0x79, 0x70, 0x74, 0x6f,
	0x6e, 0x2e, 0x64, 0x73, 0x74, 0x73, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa1, 0x01, 0x0a, 0x0f, 0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c,
	0x6d, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x3b, 0x0a, 0x0b, 0x69, 0x73, 0x73, 0x75, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x0a, 0x69, 0x73, 0x73, 0x75, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x3b, 0x0a, 0x0b,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x65,
	0x78, 0x70, 0x69, 0x72, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x22, 0xb3, 0x01, 0x0a, 0x1c, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x37, 0x0a, 0x06, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6b, 0x72, 0x79,
	0x70, 0x74, 0x6f, 0x6e, 0x2e, 0x64, 0x73, 0x74, 0x73, 0x2e, 0x44, 0x73, 0x74, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a,
	0x03, 0x74, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x69, 0x64, 0x12,
	0x2e, 0x0a, 0x13, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x6c, 0x69, 0x66, 0x65, 0x74, 0x69, 0x6d,
	0x65, 0x5f, 0x64, 0x61, 0x79, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x4c, 0x69, 0x66, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x44, 0x61, 0x79, 0x73, 0x22,
	0x8e, 0x01, 0x0a, 0x1d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c,
	0x6d, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x38, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x20, 0x2e, 0x6b, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x6e, 0x2e, 0x64, 0x73, 0x74, 0x73,
	0x2e, 0x44, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x33, 0x0a, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6b, 0x72, 0x79,
	0x70, 0x74, 0x6f, 0x6e, 0x2e, 0x64, 0x73, 0x74, 0x73, 0x2e, 0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c,
	0x6d, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x22, 0x80, 0x01, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x6d, 0x65,
	0x6e, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x37,
	0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x6b, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x6e, 0x2e, 0x64, 0x73, 0x74, 0x73, 0x2e, 0x44, 0x73,
	0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52,
	0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x74, 0x69, 0x64, 0x22, 0x8b, 0x01, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x72, 0x6f, 0x6c,
	0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x38, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6b, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x6e, 0x2e, 0x64, 0x73, 0x74,
	0x73, 0x2e, 0x44, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x33, 0x0a, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6b, 0x72,
	0x79, 0x70, 0x74, 0x6f, 0x6e, 0x2e, 0x64, 0x73, 0x74, 0x73, 0x2e, 0x45, 0x6e, 0x72, 0x6f, 0x6c,
	0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x22, 0x83, 0x01, 0x0a, 0x1c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6e, 0x72, 0x6f,
	0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x37, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6b, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x6e, 0x2e, 0x64, 0x73, 0x74,
	0x73, 0x2e, 0x44, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x74, 0x69, 0x64, 0x22, 0x96, 0x01, 0x0a, 0x1d, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x06, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6b, 0x72, 0x79, 0x70,
	0x74, 0x6f, 0x6e, 0x2e, 0x64, 0x73, 0x74, 0x73, 0x2e, 0x44, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x12, 0x3b, 0x0a, 0x0b, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x22, 0x89, 0x01, 0x0a, 0x1e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x72,
	0x6f, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x37, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6b, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x6e, 0x2e, 0x64, 0x73,
	0x74, 0x73, 0x2e, 0x44, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x88, 0x01, 0x0a,
	0x1f, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x6d,
	0x65, 0x6e, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x38, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x6b, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x6e, 0x2e, 0x64, 0x73, 0x74, 0x73, 0x2e,
	0x44, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08,
	0x69, 0x73, 0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x69, 0x73, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x61, 0x7a, 0x63, 0x2e, 0x65, 0x78, 0x74, 0x2e, 0x68, 0x70, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x4b, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x6e, 0x2f, 0x64, 0x73, 0x74, 0x73, 0x2f, 0x64, 0x73,
	0x74, 0x73, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_enrollment_token_proto_rawDescOnce sync.Once
	file_enrollment_token_proto_rawDescData = file_enrollment_token_proto_rawDesc
)

func file_enrollment_token_proto_rawDescGZIP() []byte {
	file_enrollment_token_proto_rawDescOnce.Do(func() {
		file_enrollment_token_proto_rawDescData = protoimpl.X.CompressGZIP(file_enrollment_token_proto_rawDescData)
	})
	return file_enrollment_token_proto_rawDescData
}

var file_enrollment_token_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_enrollment_token_proto_goTypes = []interface{}{
	(*EnrollmentToken)(nil),                 // 0: krypton.dsts.EnrollmentToken
	(*CreateEnrollmentTokenRequest)(nil),    // 1: krypton.dsts.CreateEnrollmentTokenRequest
	(*CreateEnrollmentTokenResponse)(nil),   // 2: krypton.dsts.CreateEnrollmentTokenResponse
	(*GetEnrollmentTokenRequest)(nil),       // 3: krypton.dsts.GetEnrollmentTokenRequest
	(*GetEnrollmentTokenResponse)(nil),      // 4: krypton.dsts.GetEnrollmentTokenResponse
	(*DeleteEnrollmentTokenRequest)(nil),    // 5: krypton.dsts.DeleteEnrollmentTokenRequest
	(*DeleteEnrollmentTokenResponse)(nil),   // 6: krypton.dsts.DeleteEnrollmentTokenResponse
	(*ValidateEnrollmentTokenRequest)(nil),  // 7: krypton.dsts.ValidateEnrollmentTokenRequest
	(*ValidateEnrollmentTokenResponse)(nil), // 8: krypton.dsts.ValidateEnrollmentTokenResponse
	(*timestamppb.Timestamp)(nil),           // 9: google.protobuf.Timestamp
	(*DstsRequestHeader)(nil),               // 10: krypton.dsts.DstsRequestHeader
	(*DstsResponseHeader)(nil),              // 11: krypton.dsts.DstsResponseHeader
}
var file_enrollment_token_proto_depIdxs = []int32{
	9,  // 0: krypton.dsts.EnrollmentToken.issued_time:type_name -> google.protobuf.Timestamp
	9,  // 1: krypton.dsts.EnrollmentToken.expiry_time:type_name -> google.protobuf.Timestamp
	10, // 2: krypton.dsts.CreateEnrollmentTokenRequest.header:type_name -> krypton.dsts.DstsRequestHeader
	11, // 3: krypton.dsts.CreateEnrollmentTokenResponse.header:type_name -> krypton.dsts.DstsResponseHeader
	0,  // 4: krypton.dsts.CreateEnrollmentTokenResponse.token:type_name -> krypton.dsts.EnrollmentToken
	10, // 5: krypton.dsts.GetEnrollmentTokenRequest.header:type_name -> krypton.dsts.DstsRequestHeader
	11, // 6: krypton.dsts.GetEnrollmentTokenResponse.header:type_name -> krypton.dsts.DstsResponseHeader
	0,  // 7: krypton.dsts.GetEnrollmentTokenResponse.token:type_name -> krypton.dsts.EnrollmentToken
	10, // 8: krypton.dsts.DeleteEnrollmentTokenRequest.header:type_name -> krypton.dsts.DstsRequestHeader
	11, // 9: krypton.dsts.DeleteEnrollmentTokenResponse.header:type_name -> krypton.dsts.DstsResponseHeader
	9,  // 10: krypton.dsts.DeleteEnrollmentTokenResponse.delete_time:type_name -> google.protobuf.Timestamp
	10, // 11: krypton.dsts.ValidateEnrollmentTokenRequest.header:type_name -> krypton.dsts.DstsRequestHeader
	11, // 12: krypton.dsts.ValidateEnrollmentTokenResponse.header:type_name -> krypton.dsts.DstsResponseHeader
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_enrollment_token_proto_init() }
func file_enrollment_token_proto_init() {
	if File_enrollment_token_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_enrollment_token_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnrollmentToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_enrollment_token_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateEnrollmentTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_enrollment_token_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateEnrollmentTokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_enrollment_token_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEnrollmentTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_enrollment_token_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEnrollmentTokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_enrollment_token_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteEnrollmentTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_enrollment_token_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteEnrollmentTokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_enrollment_token_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateEnrollmentTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_enrollment_token_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateEnrollmentTokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_enrollment_token_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enrollment_token_proto_goTypes,
		DependencyIndexes: file_enrollment_token_proto_depIdxs,
		MessageInfos:      file_enrollment_token_proto_msgTypes,
	}.Build()
	File_enrollment_token_proto = out.File
	file_enrollment_token_proto_rawDesc = nil
	file_enrollment_token_proto_goTypes = nil
	file_enrollment_token_proto_depIdxs = nil
}
