// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.2
// source: signing_key.proto

package dstsprotos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JSONWebKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Key Type - RSA
	Kty string `protobuf:"bytes,1,opt,name=kty,proto3" json:"kty,omitempty"`
	// Signing algorithm
	Alg string `protobuf:"bytes,2,opt,name=alg,proto3" json:"alg,omitempty"`
	// Key usage - Signing
	Use string `protobuf:"bytes,3,opt,name=use,proto3" json:"use,omitempty"`
	// Unique identifier for the signing key
	Kid string `protobuf:"bytes,4,opt,name=kid,proto3" json:"kid,omitempty"`
	// N value of the RSA public key used for signing tokens.
	N string `protobuf:"bytes,5,opt,name=n,proto3" json:"n,omitempty"`
	// E value of the RSA public key used for signing tokens.
	E string `protobuf:"bytes,6,opt,name=e,proto3" json:"e,omitempty"`
}

func (x *JSONWebKey) Reset() {
	*x = JSONWebKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_signing_key_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JSONWebKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSONWebKey) ProtoMessage() {}

func (x *JSONWebKey) ProtoReflect() protoreflect.Message {
	mi := &file_signing_key_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSONWebKey.ProtoReflect.Descriptor instead.
func (*JSONWebKey) Descriptor() ([]byte, []int) {
	return file_signing_key_proto_rawDescGZIP(), []int{0}
}

func (x *JSONWebKey) GetKty() string {
	if x != nil {
		return x.Kty
	}
	return ""
}

func (x *JSONWebKey) GetAlg() string {
	if x != nil {
		return x.Alg
	}
	return ""
}

func (x *JSONWebKey) GetUse() string {
	if x != nil {
		return x.Use
	}
	return ""
}

func (x *JSONWebKey) GetKid() string {
	if x != nil {
		return x.Kid
	}
	return ""
}

func (x *JSONWebKey) GetN() string {
	if x != nil {
		return x.N
	}
	return ""
}

func (x *JSONWebKey) GetE() string {
	if x != nil {
		return x.E
	}
	return ""
}

type GetSigningKeyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetSigningKeyRequest) Reset() {
	*x = GetSigningKeyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_signing_key_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSigningKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSigningKeyRequest) ProtoMessage() {}

func (x *GetSigningKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signing_key_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSigningKeyRequest.ProtoReflect.Descriptor instead.
func (*GetSigningKeyRequest) Descriptor() ([]byte, []int) {
	return file_signing_key_proto_rawDescGZIP(), []int{1}
}

type GetSigningKeyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Common RPC response header
	Header *DstsResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Token signing key - JWK
	SigningKey []*JSONWebKey `protobuf:"bytes,2,rep,name=signing_key,json=signingKey,proto3" json:"signing_key,omitempty"`
}

func (x *GetSigningKeyResponse) Reset() {
	*x = GetSigningKeyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_signing_key_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSigningKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSigningKeyResponse) ProtoMessage() {}

func (x *GetSigningKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signing_key_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSigningKeyResponse.ProtoReflect.Descriptor instead.
func (*GetSigningKeyResponse) Descriptor() ([]byte, []int) {
	return file_signing_key_proto_rawDescGZIP(), []int{2}
}

func (x *GetSigningKeyResponse) GetHeader() *DstsResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetSigningKeyResponse) GetSigningKey() []*JSONWebKey {
	if x != nil {
		return x.SigningKey
	}
	return nil
}

var File_signing_key_proto protoreflect.FileDescriptor

var file_signing_key_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x6b, 0x65, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6b, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x6e, 0x2e, 0x64, 0x73, 0x74,
	0x73, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x70, 0x0a, 0x0a, 0x4a, 0x53, 0x4f, 0x4e, 0x57, 0x65, 0x62, 0x4b, 0x65, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x74, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x61, 0x6c, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x6c,
	0x67, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x75, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x69, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x01, 0x6e, 0x12, 0x0c, 0x0a, 0x01, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01,
	0x65, 0x22, 0x16, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x67, 0x4b,
	0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x8c, 0x01, 0x0a, 0x15, 0x47, 0x65,
	0x74, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x67, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6b, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x6e, 0x2e, 0x64, 0x73,
	0x74, 0x73, 0x2e, 0x44, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x39, 0x0a,
	0x0b, 0x73, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6b, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x6e, 0x2e, 0x64, 0x73, 0x74,
	0x73, 0x2e, 0x4a, 0x53, 0x4f, 0x4e, 0x57, 0x65, 0x62, 0x4b, 0x65, 0x79, 0x52, 0x0a, 0x73, 0x69,
	0x67, 0x6e, 0x69, 0x6e, 0x67, 0x4b, 0x65, 0x79, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x61, 0x7a, 0x63, 0x2e, 0x65, 0x78, 0x74, 0x2e, 0x68, 0x70, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x4b, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x6e, 0x2f, 0x64, 0x73, 0x74, 0x73, 0x2f, 0x64,
	0x73, 0x74, 0x73, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_signing_key_proto_rawDescOnce sync.Once
	file_signing_key_proto_rawDescData = file_signing_key_proto_rawDesc
)

func file_signing_key_proto_rawDescGZIP() []byte {
	file_signing_key_proto_rawDescOnce.Do(func() {
		file_signing_key_proto_rawDescData = protoimpl.X.CompressGZIP(file_signing_key_proto_rawDescData)
	})
	return file_signing_key_proto_rawDescData
}

var file_signing_key_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_signing_key_proto_goTypes = []interface{}{
	(*JSONWebKey)(nil),            // 0: krypton.dsts.JSONWebKey
	(*GetSigningKeyRequest)(nil),  // 1: krypton.dsts.GetSigningKeyRequest
	(*GetSigningKeyResponse)(nil), // 2: krypton.dsts.GetSigningKeyResponse
	(*DstsResponseHeader)(nil),    // 3: krypton.dsts.DstsResponseHeader
}
var file_signing_key_proto_depIdxs = []int32{
	3, // 0: krypton.dsts.GetSigningKeyResponse.header:type_name -> krypton.dsts.DstsResponseHeader
	0, // 1: krypton.dsts.GetSigningKeyResponse.signing_key:type_name -> krypton.dsts.JSONWebKey
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_signing_key_proto_init() }
func file_signing_key_proto_init() {
	if File_signing_key_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_signing_key_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JSONWebKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_signing_key_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSigningKeyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_signing_key_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSigningKeyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_signing_key_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_signing_key_proto_goTypes,
		DependencyIndexes: file_signing_key_proto_depIdxs,
		MessageInfos:      file_signing_key_proto_msgTypes,
	}.Build()
	File_signing_key_proto = out.File
	file_signing_key_proto_rawDesc = nil
	file_signing_key_proto_goTypes = nil
	file_signing_key_proto_depIdxs = nil
}
